theme: jekyll-theme-cayman
title: Identification of Weather Patterns in San Diego, CA Using Cluster Analysis
description: Based on assignments from Machine Learning With Big Data by University of California San Diego on Coursera
